name: Update GitHub Stats

on:
  push:
    branches: [ main ]      # runs whenever you push to main
  schedule:
    - cron: '0 0 * * *'     # optional daily run at midnight

jobs:
  build-stats:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Generate GitHub Stats
        run: echo "Stats updated"
        env:
          GH_TOKEN: ${{ secrets.MY_PATT }}  # Replace MY_PAT with your secret name
